### ISSUE TITLE
Mostly a question.

### ISSUE THREAD

**Issue by Neumann-Valle** [cocowalla/cordova-plugin-audiorecorder#4]
It's the project abandoned?

I am planing to test it when I get home, using cordova 9 on Linux.

My app uses socket.io to send the uploaded URL to clients.. 
So I hope this works nicely.

Thanks

**Comment by Neumann-Valle** [comment]
It works with cordova 9..

Got home and tested it.. 

thanks.

**Comment by cocowalla** [comment]
It's not abandoned, it just hasn't needed any updates/fixes for a long time.

It's basically "completed software" unless there are any issues :smile:
